-- Active: 1696384805376@@127.0.0.1@3306@sayembara
CREATE TABLE users
(
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  profile VARCHAR(255) NOT NULL,
  banner VARCHAR(255) NOT NULL,
  category VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE umkm
(
  id VARCHAR(255) PRIMARY KEY,
  id_user VARCHAR(255) NOT NULL,
  verified BOOLEAN NOT NULL DEFAULT (false),
  FOREIGN KEY (id_user) REFERENCES users (id)
);

CREATE TABLE mahasiswa
(
  id VARCHAR(255) PRIMARY KEY,
  id_user VARCHAR(255) NOT NULL,
  expert BOOLEAN NOT NULL DEFAULT (false),
  FOREIGN KEY (id_user) REFERENCES users (id)
);

CREATE TABLE badge_request
(
  id_user VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_user) REFERENCES users (id)
);

CREATE TABLE verified_request
(
  id_user VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_user) REFERENCES users (id)
);

CREATE TABLE skills
(
  id VARCHAR(255) PRIMARY KEY,
  skills VARCHAR(255) NOT NULL
);

CREATE TABLE mahasiswa_skills
(
  id VARCHAR(255) PRIMARY KEY,
  id_mahasiswa VARCHAR(255) NOT NULL,
  id_skills VARCHAR(255) NOT NULL,
  FOREIGN KEY (id_mahasiswa) REFERENCES mahasiswa (id),
  FOREIGN KEY (id_skills) REFERENCES skills (id)
);

CREATE TABLE jobs
(
  id VARCHAR(255) PRIMARY KEY,
  id_user VARCHAR(255) NOT NULL,
  title VARCHAR(255),
  description TEXT,
  tags VARCHAR(255),
  deadline BIGINT,
  reward VARCHAR(255),
  draft BOOLEAN NOT NULL DEFAULT (true),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (id_user) REFERENCES users (id)
);

CREATE TABLE job_files
(
  id VARCHAR(255) PRIMARY KEY,
  id_job VARCHAR(255) NOT NULL,
  file VARCHAR(255),
  FOREIGN KEY (id_job) REFERENCES jobs (id)
);