DROP TABLE IF EXISTS job_files;

DROP TABLE IF EXISTS jobs;

DROP TABLE IF EXISTS mahasiswa_skills;

DROP TABLE IF EXISTS skills;

DROP TABLE IF EXISTS verified_request;

DROP TABLE IF EXISTS badge_request;

DROP TABLE IF EXISTS mahasiswa;

DROP TABLE IF EXISTS umkm;

DROP TABLE IF EXISTS users;